### ISSUE TITLE
Add all country rules

### ISSUE THREAD

**Issue by akaFTS** [vtex/profile-form#17]
Country rules must be migrated from checkout: https://github.com/vtex/vcs.checkout-ui/blob/master/src/script/clientprofile/clientprofile-data-vm.coffee

Currently, there's a default rule and a BRA rule but neither of them is 100% complete. Also, some features from the checkout validator such as displaying the `exempt from state registration` box still need to be created.

**Comment by klzns** [comment]
Fixed on #22
