### ISSUE TITLE
Profile rules not loading when culture is outside of Brazil.

### ISSUE THREAD

**Issue by Jayendra88** [vtex/profile-form#19]
According to the ProfileRules.js ([code](https://github.com/vtex/profile-form/blob/5f98e27d73b1107fb1755077953f8bf918cef4d1/react/ProfileRules.js#L27)), when culture is outside of Brazil it should load correct rules (rules/default.js) file. 
but try catch block at [this point](https://github.com/vtex/profile-form/blob/5f98e27d73b1107fb1755077953f8bf918cef4d1/react/ProfileRules.js#L27) does not catch the correct exception when `shouldUseIOFetching` is true.

**Comment by klzns** [comment]
#21 fixed
